config/routes.rb
Rails.application.routes.draw do
  get 'messages/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  devise_for :users

  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    # resources :messages, only: [:show, :create]
    get "messages/:id" => "messages#show", as: "message"
    post "messages/:id" => "messages#create", as: "message_post"
    resource :relationships, only: [:create, :destroy]
    get "follow" => "relationships#follow", as: "follow"
    get "followed" => "relationships#followed", as: "followed"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence:true
  validates :body, presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates :comment, presence:true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/message.rb
class Message < ApplicationRecord

  validates :message, presence:true, length:{maximum:140}

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :follower, source: :Relationship

  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followeds, through: :followed, source: :Relationship

  # has_many :messages, foreign_key: "user_id_from"

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def followed_by?(user)
    self.followed.exists?(follower_id: user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = book.id
    comment.save
    @mybook = Book.find(params[:book_id])
    @comment = BookComment.new
    # redirect_to book_path(book.id)
  end

  def destroy
    comment = BookComment.find(params[:id])
    comment.destroy
    @mybook = Book.find(params[:book_id])
    # redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @mybook = Book.find(params[:id])
    # 閲覧数の追加
    @mybook.update(viewcount: @mybook.viewcount+1)

    @user = @mybook.user
    @book = Book.new()
    @comment = BookComment.new()
  end

  def index
    @book = Book.new()
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.all.sort {|a,b|
      b.favorites.where(created_at: from...to).size <=>
      a.favorites.where(created_at: from...to).size
    }
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "You have destroyed book successfully."
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def show
    @user_to = User.find(params[:id])
    @messages = Message.where("(user_id_from=#{params[:user_id]} and user_id_to=#{params[:id]}) or (user_id_to=#{params[:user_id]} and user_id_from=#{params[:id]})")
    @message = Message.new
  end

  def create
    message = Message.new(message_params)
    message.user_id_from = params[:user_id]
    message.user_id_to = params[:id]
    message.save
    redirect_to user_message_path(params[:user_id], params[:id])
  end

  private

  def message_params
    params.require(:message).permit(:message)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    follow = Relationship.new()
    follow.follower_id = current_user.id
    follow.followed_id = params[:user_id]
    follow.save
    redirect_to request.referer
  end

  def destroy
    follows = Relationship.where(follower_id: current_user.id, followed_id: params[:user_id])
    follows.each do |follow|
      follow.destroy
    end
    redirect_to request.referer
  end

  def follow
    @relationships = Relationship.where(follower_id: params[:user_id])
  end

  def followed
    @relationships = Relationship.where(followed_id: params[:user_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comments.html.erb
<% mybook.book_comments.each do |comment| %>
  <tr>
    <td>
      <%= link_to (comment.user) do %>
        <%= image_tag comment.user.get_profile_image, size:"100x100" %><br>
        <%= comment.user.name %>
      <% end %>
    </td>
    <td><%= comment.comment %></td>
    <% if comment.user == current_user %>
      <td>
        <%= link_to 'Destroy', book_book_comment_path(comment.book, comment), remote: true, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>
      </td>
    <% end %>
  </tr>
<% end %>

app/views/book_comments/create.js.erb
$('.comment-area').html("<%= j(render "book_comments/comments", mybook: @mybook) %>");
$('#book_comment_comment').val('')

app/views/book_comments/destroy.js.erb
$('.comment-area').html("<%= j(render "book_comments/comments", mybook: @mybook) %>");

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group row" id="star">
    <%= f.label :star,'評価 ', class:'col-md-3 col-form-label' %>
    <%= f.hidden_field :star, id: :review_star %>
  </div>
  <script>
    $('#star').raty({
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      scoreName: 'book[star]' //登録するモデル名とカラム名を記述
    });
  </script>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td class="favorite_buttons_<%= book.id %>">
          <%= render 'favorites/favorite', book: book %>
        </td>
        <td>
          コメント数:<%= book.book_comments.count %>
        </td>
        <td>
          閲覧数:<%= book.viewcount %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@mybook.user) do %>
            <%= image_tag @mybook.user.get_profile_image, size:"100x100" %><br>
            <%= @mybook.user.name %>
            <% end %>
          </td>
          <td><%= link_to @mybook.title, @mybook %></td>
          <td><%= @mybook.body %></td>
          <td>
            <% if @mybook.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(@mybook), method: :delete do %>
                ♥ <%= @mybook.favorites.count %> いいね
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(@mybook), method: :post do %>
                ♡ <%= @mybook.favorites.count %> いいね
              <% end %>
            <% end %>
          </td>
          <td>
            コメント数:<%= @mybook.book_comments.count %>
          </td>
          <td>
            閲覧数:<%= @mybook.viewcount %>
          </td>
          <% if @user.id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@mybook), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @mybook, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>

      <!--コメント一覧表示-->
      <h3>Comments</h3>
      <table class='table'>
        <tbody class='comment-area'>
          <%= render 'book_comments/comments', mybook: @mybook %>
        </tbody>
      </table>
      <!--新規コメント入力-->
      <%= form_with model:[@mybook, @comment], local:false do |f| %>
        <div class="form-group">
          <%= f.label :comment %>
          <%= f.text_area :comment, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), remote: true, method: :delete do %>
    ♥ <%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), remote: true, method: :post do %>
    ♡ <%= book.favorites.count %> いいね
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('.favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$('.favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/messages/show.html.erb
<h1><%= @user_to.name %>さんとのチャット</h1>

<div class="container">
  <% @messages.each do |message| %>
    <div class="row">
      <%= message.message %>
    </div>
  <% end %>
</div>

<div class="container">
  <div class="row">
    <div class="col-9 justify-content-start">
      <%= form_with model: @message, url: user_message_post_path(current_user.id, params[:id]) do |f| %>
        <div class="form-group">
          <%= f.text_field :message, class: 'form-control' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/relationships/follow.html.erb
<div class='container'>
  <h1>Follow Users</h1>
  <div class='row'>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @relationships.each do |relationship| %>
          <tr>
            <td><%= image_tag relationship.followed.get_profile_image, size: '50x50' %></td>
            <td><%= relationship.followed.name %></td>
            <td>フォロー数: <%= relationship.followed.follower.count %></td>
            <th>フォロワー数: <%= relationship.followed.followed.count %></td>
            <td><%= link_to 'Show', relationship.followed %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/relationships/followed.html.erb
<div class='container'>
  <h1>Followed Users</h1>
  <div class='row'>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @relationships.each do |relationship| %>
          <tr>
            <td><%= image_tag relationship.follower.get_profile_image, size: '50x50' %></td>
            <td><%= relationship.follower.name %></td>
            <td>フォロー数: <%= relationship.follower.follower.count %></td>
            <th>フォロワー数: <%= relationship.follower.followed.count %></td>
            <td><%= link_to 'Show', relationship.follower %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>
          <% if user != current_user %>
            <% if user.followed_by?(current_user) %>
              <%= link_to user_relationships_path(user), method: :delete do%>
                <i class="fas fa-user-minus"></i> フォローを外す
              <% end %>
            <% else %>
              <%= link_to user_relationships_path(user), method: :post do%>
                <i class="fas fa-user-plus"></i> フォローをする
              <% end %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%=link_to user.follower.count, user_follow_path(user.id) %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%=link_to user.followed.count, user_followed_path(user.id)%></th>
  </tr>
</table>

<div class="row">
  <% if user != current_user %>
    <div class="col">
      <% if user.followed_by?(current_user) %>
        <%= link_to user_relationships_path(user), method: :delete, class: "btn btn-light btn-block" do%>
          <i class="fas fa-user-minus"></i> フォローを外す
        <% end %>
      <% else %>
        <%= link_to user_relationships_path(user), method: :post, class: "btn btn-info btn-block" do%>
          <i class="fas fa-user-plus"></i> フォローをする
        <% end %>
      <% end %>
    </div>
    <div class="col">
      <% if current_user.followed_by?(user) and user.followed_by?(current_user)%>
        <%= link_to "チャットする", user_message_path(current_user.id, user.id)%>
      <% end %>
    </div>
  <% end %>
</div>


<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block mt-3" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>